Controllers/InicioController.cs
using AutentificacionAutorizacion.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutentificacionAutorizacion.Datos;
using AutentificacionAutorizacion.Servicios;
using AutentificacionAutorizacion.Negocio;
using AutentificacionAutorizacion.ViewModels;
using System.Text.RegularExpressions;

namespace AutentificacionAutorizacion.Controllers
{
    public class InicioController : Controller
    {
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string correo, string clave)
        {
            Usuario usuario = DBUsuario.Validar(correo, UtilidadServicio.ConvertirSHA256(clave));

            if (usuario != null)
            {
                if (!usuario.Confirmado)
                {
                    ViewBag.Mensaje = $"Falta confirmar su cuenta. Se le envio un correo a {correo}";
                }
                else if (usuario.Restablecer)
                {
                    ViewBag.Mensaje = $"Se ha solicitado restablecer su cuenta, favor revise su bandeja del correo {correo}";
                }
                else
                {
                    int rol = UsuariosRolesActor.ObtenerRol(usuario);

                    if(rol == 2)
                    {
                        Session["rol"] = rol;
                        Session["usuario"] = usuario;
                        return RedirectToAction("Index", "Admin");
                    }
                    else
                    {
                        Correo correoDTO = new Correo()
                        {
                            Para = correo,
                            Asunto = "Token de seguridad"
                        };

                        string tokenEnviado = CorreoServicio.EnviarToken(correoDTO);
                        Session["usuario"] = usuario;
                        Session["tokenEnviado"] = tokenEnviado;

                        return RedirectToAction("Index", "DosPasos");
                        //return RedirectToAction("Index", "Home");
                    }
                }

            }
            else
            {
                ViewBag.Mensaje = "No se encontraron coincidencias";
            }


            return View();
        }

        public ActionResult Registrar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Registrar(Usuario usuario)
        {
            if (usuario.Clave != usuario.ConfirmarClave)
            {
                ViewBag.Nombre = usuario.Nombre;
                ViewBag.Correo = usuario.Correo;
                ViewBag.Mensaje = "Las contraseñas no coinciden";
                return View();
            }

            if (DBUsuario.Obtener(usuario.Correo) == null)
            {
                usuario.Clave = UtilidadServicio.ConvertirSHA256(usuario.Clave);
                usuario.Token = UtilidadServicio.GenerarToken();
                usuario.Restablecer = false;
                usuario.Confirmado = false;
                bool respuesta = DBUsuario.Registrar(usuario);

                if (respuesta)
                {
                    string path = HttpContext.Server.MapPath("~/Plantilla/Confirmar.html");
                    string content = System.IO.File.ReadAllText(path);
                    string url = string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Headers["host"], "/Inicio/Confirmar?token=" + usuario.Token);

                    string htmlBody = string.Format(content, usuario.Nombre, url);

                    Correo correoDTO = new Correo()
                    {
                        Para = usuario.Correo,
                        Asunto = "Correo confirmacion",
                        Contenido = htmlBody
                    };

                    bool enviado = CorreoServicio.Enviar(correoDTO);
                    ViewBag.Creado = true;
                    ViewBag.Mensaje = $"Su cuenta ha sido creada. Hemos enviado un mensaje al correo {usuario.Correo} para confirmar su cuenta";

                    Usuario usuarioCreado = DBUsuario.Obtener(usuario.Correo);

                    UsuariosRolesActor.CrearRegistro(usuarioCreado);



                }
                else
                {
                    ViewBag.Mensaje = "No se pudo crear su cuenta";
                }



            }
            else
            {
                ViewBag.Mensaje = "El correo ya se encuentra registrado";
            }


            return View();
        }

        public ActionResult Confirmar(string token)
        {
            ViewBag.Respuesta = DBUsuario.Confirmar(token);
            return View();
        }

        //public ActionResult Restablecer()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public ActionResult Restablecer(string correo)
        //{

        //    Usuario usuario = DBUsuario.Obtener(correo);
        //    ViewBag.Correo = correo;
        //    if (usuario != null)
        //    {
        //        bool respuesta = DBUsuario.RestablecerActualizar(1, usuario.Clave, usuario.Token);

        //        if (respuesta)
        //        {
        //            string path = HttpContext.Server.MapPath("~/Plantilla/Restablecer.html");
        //            string content = System.IO.File.ReadAllText(path);
        //            string url = string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Headers["host"], "/Inicio/Actualizar?token=" + usuario.Token);

        //            string htmlBody = string.Format(content, usuario.Nombre, url);

        //            Correo correoDTO = new Correo()
        //            {
        //                Para = correo,
        //                Asunto = "Restablecer cuenta",
        //                Contenido = htmlBody
        //            };

        //            bool enviado = CorreoServicio.Enviar(correoDTO);
        //            ViewBag.Restablecido = enviado;
        //        }
        //        else
        //        {
        //            ViewBag.Mensaje = "No se pudo restablecer la cuenta";
        //        }

        //    }
        //    else
        //    {
        //        ViewBag.Mensaje = "No se encontraron coincidencias con el correo";
        //    }

        //    return View();
        //}


        [HttpPost]
        public ActionResult Restablecer(string correo)
        {
            // Validación básica de la entrada de correo
            if (!Regex.IsMatch(correo, @"^[^@\s]+@[^@\s]+\.[^@\s]+$", RegexOptions.IgnoreCase))
            {
                ViewBag.Mensaje = "Formato de correo no válido.";
                return View();
            }

            try
            {
                Usuario usuario = DBUsuario.Obtener(correo);
                ViewBag.Correo = correo;
                if (usuario != null)
                {
                    bool respuesta = DBUsuario.RestablecerActualizar(1, usuario.Clave, usuario.Token);

                    if (respuesta)
                    {
                        string path = HttpContext.Server.MapPath("~/Plantilla/Restablecer.html");
                        string content = System.IO.File.ReadAllText(path);
                        string url = $"{Request.Url.Scheme}://{Request.Url.Authority}/Inicio/Actualizar?token={HttpUtility.UrlEncode(usuario.Token)}";

                        string htmlBody = string.Format(content, usuario.Nombre, url);

                        Correo correoDTO = new Correo()
                        {
                            Para = correo,
                            Asunto = "Restablecer cuenta",
                            Contenido = htmlBody
                        };

                        bool enviado = CorreoServicio.Enviar(correoDTO);
                        ViewBag.Restablecido = true;
                    }
                    else
                    {
                        ViewBag.Mensaje = "No se pudo restablecer la cuenta";
                    }
                }
                else
                {
                    ViewBag.Mensaje = "No se encontraron coincidencias con el correo";
                }
            }
            catch (Exception ex)
            {
                // Log the exception details
                ViewBag.Mensaje = "Ocurrió un error al procesar su solicitud.";
            }

            return View();
        }


        public ActionResult Actualizar(string token)
        {
            ViewBag.Token = token;
            return View();
        }

        [HttpPost]
        public ActionResult Actualizar(string token, string clave, string confirmarClave)
        {
            ViewBag.Token = token;
            if (clave != confirmarClave)
            {
                ViewBag.Mensaje = "Las contraseñas no coinciden";
                return View();
            }

            bool respuesta = DBUsuario.RestablecerActualizar(0, UtilidadServicio.ConvertirSHA256(clave), token);

            if (respuesta)
                ViewBag.Restablecido = true;
            else
                ViewBag.Mensaje = "No se pudo actualizar";

            return View();
        }
    }

}

Controllers/InvitadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutentificacionAutorizacion.Controllers
{
    public class InvitadoController : Controller
    {
        // GET: Invitado
        public ActionResult Index()
        {
            Session["rol"] = null;
            Session["usuario"] = null;
            return View("MapInvitado");
        }

        public ActionResult Salir()
        {
            return RedirectToAction("Login", "Inicio");
        }
    }
}

Views/Inicio/Actualizar.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Actualizar</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link rel="stylesheet" href="~/Estilos/LoginRegistro.css">
</head>
<body>
    <div class="container">

        <div class="col-5">

            <div class="card">
                <div class="card-header"><h3 class="text-center">Restablecer Contraseña</h3></div>
                <div class="card-body">
                    @if (ViewBag.Restablecido == null)
                    {
                        <form action="@Url.Action("Actualizar","Inicio")" method="post">
                            <input type="hidden" name="token" value="@ViewBag.Token" />

                            <div class="mb-3">
                                <label>Ingresar una nueva contraseña</label>
                                <input type="password" class="form-control" name="clave" required />
                            </div>
                            <div class="mb-3">
                                <label>Confirmar contraseña</label>
                                <input type="password" class="form-control" name="confirmarClave" required />
                            </div>

                            @if (ViewBag.Mensaje != null)
                            {
                                <div class="alert alert-danger">
                                    @ViewBag.Mensaje
                                </div>
                            }

                            <div class="mb-3">
                                <div class="d-grid">
                                    <button class="btn btn-primary" type="submit">Cambiar contraseña</button>
                                </div>
                            </div>


                        </form>
                    }
                    else
                    {
                        <div class="alert alert-success">
                            <p>Su contraseña fue restablecida, ahora puede ingresar a su cuenta con su nueva clave.</p>
                            <a class="btn btn-success" href="@Url.Action("Login","Inicio")">Ingresar</a>
                        </div>
                    }
                </div>
            </div>

        </div>
    </div>
        @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

Views/Inicio/Confirmar.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Confirmar</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link rel="stylesheet" href="~/Estilos/LoginRegistro.css">
</head>
<body>
    <div class="container">
        @if ((bool)ViewBag.Respuesta)
        {
            <div class="alert alert-success">
                <p><b>Listo!</b>&nbsp; Su cuenta fue confirmada. Ahora puede acceder</p>
                <a class="btn btn-success" href="@Url.Action("Login","Inicio")">Ingresar</a>
            </div>
        }
        else
        {
            <div class="alert alert-danger">
                <p>No se pudo confirmar el correo</p>
            </div>
        }
    </div>
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

Views/Inicio/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link href="~/Estilos/LoginRegistro.css" rel="stylesheet" />

</head>
<body class="nada">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-4">
                <div class="card">
                    <div class="card-header text-center">
                        <img src="~/Estilos/Imagenes/Logos/logopetmap.png" class="img-fluid" alt="Logo">
                    </div>
                    <div class="card-body">

                        <form action="@Url.Action("Login","Inicio")" method="post">
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                                    </div>
                                    <input type="email" class="form-control" name="correo" required placeholder="Correo" />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                                    </div>
                                    <input type="password" class="form-control" name="clave" required placeholder="Contraseña">
                                </div>
                            </div>
                            @if (ViewBag.Mensaje != null)
                            {
                                <div class="alert alert-danger">
                                    @ViewBag.Mensaje
                                </div>
                            }
                            <div class="form-group">
                                <button type="submit" id="submitBtn" class="btn btn-primary btn-block">Iniciar Sesión</button>
                            </div>
                            <div class="mb-3">
                                <div class="d-grid">
                                    <a class="btn btn-secondary btn-block" href="@Url.Action("Index", "Invitado")">Ingresar como invitado</a>
                                </div>
                            </div>
                            <div class="card-footer text-center">
                                <div style="color:white">
                                    No tienes cuenta? registrate <a href="@Url.Action("Registrar","Inicio")" style="color: #FFC312;">Aqui</a>
                                    <br />
                                    Has olvidado tu contraseña? recuperala <a href="@Url.Action("Restablecer","Inicio")" style="color: #FFC312;">Aqui</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
        @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

Views/Inicio/Registrar.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>Registrar</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link rel="stylesheet" href="~/Estilos/LoginRegistro.css">
</head>
<body>
    <div class="container d-flex justify-content-center align-items-center vh-100">
        <div class="col-md-6 col-lg-4">
            <div class="card">
                <div class="card-header"><h3 class="text-center">Registrar cuenta</h3></div>
                <div class="card-body">

                    @if (ViewBag.Creado == null)
                    {
                        <form action="@Url.Action("Registrar","Inicio")" method="post">

                            <div class="text-color mb-3">
                                <label>Nombre</label>
                                <input type="text" class="form-control" name="Nombre" value="@(ViewBag.Nombre !=null ? ViewBag.Nombre : "")" required />
                            </div>
                            <div class="text-color mb-3" ">
                                <label>Correo</label>
                                <input type="email" class="form-control" name="Correo" value="@(ViewBag.Correo !=null ? ViewBag.Correo : "")" required />
                            </div>
                            <div class="text-color mb-3" ">
                                <label>Contraseña</label>
                                <input type="password" class="form-control" name="Clave" required />
                            </div>
                            <div class="text-color mb-3">
                                <label>Confirmar Contraseña</label>
                                <input type="password" class="form-control" name="ConfirmarClave" required />
                            </div>

                            @if (ViewBag.Mensaje != null)
                            {
                                <div class="alert alert-danger">
                                    @ViewBag.Mensaje
                                </div>
                            }

                            <div class="mb-3">
                                <div class="d-grid">
                                    <button class="btn btn-primary btn-block" type="submit">Registrarse</button>
                                </div>
                            </div>
                            <div class="card-footer text-center">
                                Ya tienes una cuenta? 
                                <br /><a href="@Url.Action("Login","Inicio")" style="color: #FFC312;">Inicia sesion</a>
                            </div>
                        </form>

                    }
                    else
                    {
                        <div class="alert alert-success">
                            <p>@ViewBag.Mensaje</p>
                            <a class="btn btn-success" href="@Url.Action("Login","Inicio")">Ingresar</a>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

Views/Inicio/Restablecer.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Restablecer</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link rel="stylesheet" href="~/Estilos/LoginRegistro.css">
</head>
<body>
    <div class="container">
        <div class="col-md-6 col-lg-4">
            <div class="card">
                <div class="card-header"><h3 class="text-center">Restablecer cuenta</h3></div>
                <div class="card-body">
                    @if (ViewBag.Restablecido == null)
                    {
                        <form action="@Url.Action("Restablecer","Inicio")" method="post">
                            <p class="text-color mb-3" style="text-align: center">Ingrese su correo y le enviaremos un enlace para restablecer su contraseña.</p>

                            <div class="mb-3">
                                <label>Correo</label>
                                <input type="email" class="form-control" name="correo" value="@(ViewBag.Correo !=null ? ViewBag.Correo : "")" required />
                            </div>

                            @if (ViewBag.Mensaje != null)
                            {
                                <div class="alert alert-danger">
                                    @ViewBag.Mensaje
                                </div>
                            }

                            <div class="mb-3">
                                <div class="d-grid">
                                    <button class="btn btn-primary" type="submit">Restablecer</button>
                                    <a class="btn btn-link" style="color: white" href="@Url.Action("Login","Inicio")">Volver</a>
                                </div>
                            </div>


                        </form>
                    }
                    else
                    {
                        <div class="alert alert-success">
                            <p>Su contraseña fue restablecida, le enviamos un mensaje su correo para restablecer.</p>
                            <a class="btn btn-success" href="@Url.Action("Login","Inicio")">Ingresar</a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>